siigo/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
siigo/client.py,sha256=t46KnbV-thxrtVKMZ-WmChf55UY6MOx41FlfYyJdQME,10791
siigo/exceptions.py,sha256=5dxEIHF_4wrK6-W_NZk9BJuESR_YILWMiuUp70XvoDE,190
siigo_python-0.1.0.dist-info/LICENSE,sha256=Uqi0JaqS9pBHVpNzcpBHvkGqpeRCru4Y6tFH90V-WH8,1065
siigo_python-0.1.0.dist-info/METADATA,sha256=rWjoBtjsQc9kS0rq7iFJhOSzlUXlSMgLSwTD7HJlifc,6614
siigo_python-0.1.0.dist-info/WHEEL,sha256=7Z8_27uaHI_UZAc4Uox4PpBhQ9Y5_modZXWMxtUi4NU,88
siigo_python-0.1.0.dist-info/RECORD,,
